name: "cf-sf-deploy-dynamic-apex"
description: "Deploys metadata and runs Apex tests with the “Dynamic Apex” parameter"
author: "Cloudfulcrum"

inputs:
  sf_metadatapath:
    description: "Metadata path for deploy"
    required: true
  sf_url:
    description: "Salesforce instance URL"
    required: true
  sf_username:
    description: "Salesforce username"
    required: true
  sf_password:
    description: "Salesforce password"
    required: true
  sf_accesstoken:
    description: "Salesforce access token"
    required: false
  sf_testlevel:
    description: "Test level for deployment"
    required: false
    default: "RunTestsBasedOnChanges"
  sf_nocheckonly:
    description: "Check-only deployment"
    required: false
    default: "false"

branding:
  icon: "upload-cloud"
  color: "blue"

runs:
  using: "docker"
  image: "./sfdx-deploy/Dockerfile"