name: "cf-sf-smart-deploy"
description: "Deploys the metadata bundle to Salesforce"
author: "CloudFulcrum"

inputs:
  sf_metadatapath:
    description: "Metadata path for deploy"
    required: true
  sf_url:
    description: "Salesforce instance URL"
    required: true
  sf_username:
    description: "Salesforce username"
    required: true
  sf_password:
    description: "Salesforce password"
    required: true
  sf_testlevel:
    description: "Test level for deployment"
    required: true
  sf_nocheckonly:
    description: "Check-only deployment"
    required: false
    default: "false"

branding:
  icon: "upload-cloud"
  color: "blue"

runs:
  using: "docker"
  image: "./sfdx-deploy/Dockerfile"