name: "Salesforce Deployment Accelerator GitHub Action - Deploy"
description: "Deploy Salesforce metadata using SF"
author: "Cloudfulcrum"

inputs:
  sf_url:
    description: "Salesforce instance URL"
    required: true
  sf_username:
    description: "Salesforce username"
    required: true
  sf_password:
    description: "Salesforce password"
    required: true
  sf_testlevel:
    description: "Test level for deployment"
    required: false
    default: ""
  sf_nocheckonly:
    description: "Check-only deployment"
    required: false
    default: "false"

branding:
  icon: "upload-cloud"
  color: "blue"

runs:
  using: "docker"
  image: "./sfdx-deploy/Dockerfile"