name: Publish Docker Images
on:
  push:
    branches:
      - main  # Only run when code is pushed to main
    paths:
      - "cf-sf-*/**"  # Trigger only if action folders change

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Allow pushing to GitHub Container Registry
      contents: read

    strategy:
      matrix:
        action: [cf-sf-lean-packager, cf-sf-smart-deploy, cf-sf-deploy-dynamic-apex, cf-sf-apex-cache-builder, cf-sf-secure-quality-gate]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Tag
        id: tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.action }}:${{ env.IMAGE_TAG }}
          LATEST_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.action }}:latest

          docker build -t $IMAGE_NAME -t $LATEST_IMAGE_NAME ${{ matrix.action }}
          docker push $IMAGE_NAME
          docker push $LATEST_IMAGE_NAME