name: Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeql-scan:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  dependency-scan:
    name: Java Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Salesforce-GitHub-Actions"
          path: cf-sf-lean-packager
          format: "HTML"

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v3
        with:
          name: Dependency-Report
          path: dependency-check-report.html

  docker-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - name: Scan Docker Image
        run: |
          trivy image ghcr.io/${{ github.repository_owner }}/cf-sf-lean-packager:latest